### ISSUE TITLE
Missing Schema Pallet

### ISSUE THREAD

**Issue by dploeger** [tangram-js/json-editor#1]
I wanted to use the json-editor for schema creation, but in the current version, the schema pallet is not available anymore.

**Comment by dploeger** [comment]
Oh, I just understood, that the editor was not able to edit schemas anymore, just to validate against them. Sorry.

**Comment by tangram-js** [comment]
You still can edit JSON schema with json-editor, but with slightly different way:
1. Select "json_schema" in the pallet of user schemas.
2. Right-click on the tree node of JSON to bring out the context menu.
3. Use the "Append" drop down menu to select the schema element and append into the JSON tree.
4. Update the schema as normal JSON document.
