### ISSUE TITLE
Provide a privacy policy

### ISSUE THREAD

**Issue by coopernetes** [tangram-js/json-editor#30]
Hi,
This looks to be a very useful tool for creating new JSON schemas. However, I could not find any policy on how user data (email addresses) would be handled by the operator of the service. It would be nice to know how this data is being handled before asking people to hand over their email address and sign up for using the site.

**Comment by tangram-js** [comment]
Thank you for your advice! The demo website use Firebase for authentication and store schema data, email is required just for Firebase authentication.
I will add a declaration for the usage of email.
