### ISSUE TITLE
Schema load and save does not understand JSON meta schema de

### ISSUE THREAD

**Issue by sei-vsarvepalli** [tangram-js/json-editor#31]
I just tried to load JSON schema definition from a project https://github.com/CVEProject/cve-schema/blob/master/schema/v5.0/CVE_JSON_5.0_schema.json as example to see if schema can be loaded and edited. It looks like the "$id" and "$schema" all cause errors when trying to load them 

> Save custom schema error: Reference.set failed: First argument contains an invalid key ($id) in property 'schemas.iFWGZGBb0sUc4nef4Cmu8zX6IMf2.'. Keys must be non-empty strings and can't contain ".", "#", "$", "/", "[", or "]"

It does not look like it supports saving the schema with any of the json schema meta schema information.

**Comment by tangram-js** [comment]
The demo website use Firebase to store schema, the error message comes from Firebase, looks like it can't accept key with '$' character, this issue could be solved by apply url encode before store the key and apply url decode after retrieve the key.

**Comment by idjhuang** [comment]
The actual problem is the title of schema, it is used as key of whole schema, after apply url encode/decode, this issue is solved.

**Comment by tangram-js** [comment]
The content of schema already applied url encode/decode.
The actual problem is the title of schema, it is used as key of whole schema.
After apply url encode/decode on the title, this issue is solved.

**Comment by tangram-js** [comment]
The actual problem is the '.' in the key, the encodeURIComponent left the '.' and cause error from Firebase.
This issue is solved by adding extra encode/decode for '.' character.
